services:
  symfony:
    build:
      context: ../backend/  
    depends_on:
      - postgres_db 
    ports:
      - "8000:80" 
    networks:
      - backend_network 

networks:
  backend_network:
    external: true  
